import dotenv from "dotenv";

dotenv.config();

const config = {
  port: process.env.PORT || 8080,
  nodeEnv: process.env.NODE_ENV || "development",
};

export default config;

export const errorCode = {
  VALIDATION_ERROR: "VALIDATION_ERROR",
  INTERNAL_SERVER_ERROR: "INTERNAL_SERVER_ERROR",
  UNAUTHENTICATED: "UNAUTHENTICATED_ERROR",
  ATTACK_DETECTED: "ATTACK_DETECTED_ERROR",
  ACCESS_TOKEN_EXPIRED: "ACCESS_TOKEN_EXPIRED",
  USER_ALREADY_EXISTS: "USER_ALREADY_EXISTS",
  OVER_REQUEST_LIMIT: "OVER_REQUEST_LIMIT",
  OTP_EXPIRED: "OTP_EXPIRED",
  ACCOUNT_FROZEN: "ACCOUNT_FROZEN",
  UNAUTHORIZED: "UNAUTHORIZED_ERROR",
  MAINTENANCE_MODE: "MAINTENANCE_MODE",
  BAD_REQUEST: "BAD_REQUEST",
};
